name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Debug info
        run: |
          node --version
          npm --version
      - name: Build
        run: |
          npm ci
          npm run build
